blog/urls.py
from django.urls import path
from .views import main, by_rubric, post_detail

app_name = 'blog'

urlpatterns = [
    path('', main, name='main'),
    path('<int:rubric_id>/', by_rubric, name='by_rubric'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', post_detail,
            name='post_detail'),
]

pyblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from blog import views as blog_views

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', RedirectView.as_view(url='/blog/', permanent=True)),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name = 'django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
from django.utils import timezone
from django.db import models
from django.urls import reverse


# Create your models here.
class Post(models.Model):
    STATUS_CHOICES = (
        ('черновик', 'Черновик'),
        ('опубликовано', 'Опубликовано'),
    )
    rubric = models.ForeignKey('Rubric', null=True,
    on_delete=models.PROTECT, verbose_name='Рубрика')
    title = models.CharField(max_length=250, verbose_name = 'Заголовок')
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    body = models.TextField(verbose_name='Текст')
    publish = models.DateTimeField(default=timezone.now, verbose_name='Публиковать')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=12,
                              choices=STATUS_CHOICES,
                              default='draft', verbose_name='Статус')
    class Meta:
        ordering = ('-publish',)
        verbose_name_plural = 'Посты'
        verbose_name = 'Пост'

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


    def __str__(self):
        return self.title

class Rubric(models.Model):
    name = models.CharField(max_length=20, db_index=True, verbose_name='Название')

    class Meta:
        verbose_name_plural = 'Рубрики'
        verbose_name = 'Рубрика'
        ordering = ['name']

    def __str__(self):
        return self.name

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from django.core.paginator import Paginator

# Create your views here.

def main(request):
    posts=Post.objects.filter(status='опубликовано')
    rubrics = Rubric.objects.all()
    paginator = Paginator(posts, 5)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'posts':page.object_list, 'page': page, 'rubrics':rubrics}
    return render(request, 'blog/main.html', context)

def by_rubric(request, rubric_id):
    posts=Post.objects.filter(status='опубликовано').filter(rubric=rubric_id)
    rubrics = Rubric.objects.all()
    current_rubric = Rubric.objects.get(pk=rubric_id)
    context = {'posts':posts, 'rubrics':rubrics, 'current_rubric':current_rubric}
    return render(request, 'blog/by_rubric.html', context)


def post_detail(request,year,month,day,post):
    post = get_object_or_404(Post, slug=post,
            status='опубликовано',
            publish__year=year,
            publish__month=month,
            publish__day=day)
    rubrics = Rubric.objects.all()
    context = {'post':post, 'rubrics': rubrics}

    return render(request,
            'blog/detail.html',
            context)

blog/templates/blog/by_rubric.html
{% extends "layout/basic.html" %}
{% block title %}{{current_rubric.name}}{% endblock %}

{% block content %}
<h1>Рубрика: {{current_rubric.name}}</h1>
    {% for post in posts %}
    <div>
        <h2><a href="{{ post.get_absolute_url }}">
                {{post.title}}</a></h2>
        <p>{{ post.body|truncatewords:30|safe|linebreaksbr }}</p>
        <p class="date">Опубликовано {{ post.publish }}</p>
    </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/detail.html
{% extends "layout/basic.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">Опубликовано {{ post.publish }}</p>
    {{ post.body|safe|linebreaks }}
{% endblock %}

blog/templates/blog/main.html
{% extends "layout/basic.html" %}
{% block content %}
     <h1 class="title">Список статей:</h1>
    {% for post in posts %}
    <div>
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{post.title}}</a>
        </h2>
        <p>{{ post.body|truncatewords:30|safe|linebreaksbr }}</p>
        <p class="date">Опубликовано {{ post.publish }}</p>
    </div>
    {% endfor %}
    {% include "pagination.html" %}
{% endblock %}

blog/templates/layout/basic.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type"
        content="text/html; charset=utf-8">
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
        <title>{% block title %}Главная{% endblock %} - ABOBGEKKON</title>
    </head>
    <body>
        <div class="header">
            <h2 id="site_name">ABOBGEKKON</h2>
            <p>IT-блог от новичка для новичков</p>
        </div>
        <div class="container">
            <div class="left">
                <nav>
                <a href="{% url 'blog:main' %}">Главная</a>
                {% for rubric in rubrics %}
                <a href="{% url 'blog:by_rubric' rubric.pk %}">{{rubric.name}}</a>
                {% endfor %}
                </nav>
            </div>
            <div class="body">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <div class="footer">
            <p>Контактная информация:
            <a href="mailto:abobgekkon@gmail.com">abobgekkon@gmail.com</a></p>
            <p>Код сайта: <a href="https://github.com/abobgekkon/pyblog">https://github.com/abobgekkon/pyblog</a></p>
        </div>
    </body>
</html>

blog/templates/pagination.html
<div class="pagination">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Назад</a>
    {% endif %}
    Страница {{ page.number }} из {{ page.paginator.num_pages }}.
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Вперёд</a>
    {% endif %}
</div>